[package]
name = "h10_language_server"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
serde_json = "1.0.108"
tokio = { version = "1.35.1", features = ["rt", "io-std", "rt-multi-thread"] }
tower-lsp = "0.20.0"
